//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIDE.DAL.MDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeshToChar
    {
        public long MeshID { get; set; }
        public long EC_ID { get; set; }
    }
}
