//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.5477
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class scene {
    
    private sceneResourceLocation[] resourceLocationsField;
    
    private sceneEnvironment environmentField;
    
    private sceneTerrain terrainField;
    
    private sceneLight lightField;
    
    private sceneCamera[] cameraField;
    
    private sceneNode[] nodesField;
    
    private string formatVersionField;
    
    private string generatorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("resourceLocation", IsNullable=false)]
    public sceneResourceLocation[] resourceLocations {
        get {
            return this.resourceLocationsField;
        }
        set {
            this.resourceLocationsField = value;
        }
    }
    
    /// <remarks/>
    public sceneEnvironment environment {
        get {
            return this.environmentField;
        }
        set {
            this.environmentField = value;
        }
    }
    
    /// <remarks/>
    public sceneTerrain terrain {
        get {
            return this.terrainField;
        }
        set {
            this.terrainField = value;
        }
    }
    
    /// <remarks/>
    public sceneLight light {
        get {
            return this.lightField;
        }
        set {
            this.lightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("camera")]
    public sceneCamera[] camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("node", IsNullable=false)]
    public sceneNode[] nodes {
        get {
            return this.nodesField;
        }
        set {
            this.nodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formatVersion {
        get {
            return this.formatVersionField;
        }
        set {
            this.formatVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string generator {
        get {
            return this.generatorField;
        }
        set {
            this.generatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneResourceLocation {
    
    private string typeField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironment {
    
    private sceneEnvironmentScenemanager scenemanagerField;
    
    private sceneEnvironmentColourAmbient colourAmbientField;
    
    private sceneEnvironmentSkyDome skyDomeField;
    
    private sceneEnvironmentFog fogField;
    
    private sceneEnvironmentViewport viewportField;
    
    private sceneEnvironmentCamera cameraField;
    
    /// <remarks/>
    public sceneEnvironmentScenemanager scenemanager {
        get {
            return this.scenemanagerField;
        }
        set {
            this.scenemanagerField = value;
        }
    }
    
    /// <remarks/>
    public sceneEnvironmentColourAmbient colourAmbient {
        get {
            return this.colourAmbientField;
        }
        set {
            this.colourAmbientField = value;
        }
    }
    
    /// <remarks/>
    public sceneEnvironmentSkyDome skyDome {
        get {
            return this.skyDomeField;
        }
        set {
            this.skyDomeField = value;
        }
    }
    
    /// <remarks/>
    public sceneEnvironmentFog fog {
        get {
            return this.fogField;
        }
        set {
            this.fogField = value;
        }
    }
    
    /// <remarks/>
    public sceneEnvironmentViewport viewport {
        get {
            return this.viewportField;
        }
        set {
            this.viewportField = value;
        }
    }
    
    /// <remarks/>
    public sceneEnvironmentCamera camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentScenemanager {
    
    private string nameField;
    
    private uint idField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentColourAmbient {
    
    private decimal rField;
    
    private decimal gField;
    
    private decimal bField;
    
    private byte aField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal r {
        get {
            return this.rField;
        }
        set {
            this.rField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal g {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte a {
        get {
            return this.aField;
        }
        set {
            this.aField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentSkyDome {
    
    private bool activeField;
    
    private string materialField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string material {
        get {
            return this.materialField;
        }
        set {
            this.materialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentFog {
    
    private sceneEnvironmentFogColour colourField;
    
    private string modeField;
    
    private byte startField;
    
    private ushort endField;
    
    private byte densityField;
    
    /// <remarks/>
    public sceneEnvironmentFogColour colour {
        get {
            return this.colourField;
        }
        set {
            this.colourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte density {
        get {
            return this.densityField;
        }
        set {
            this.densityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentFogColour {
    
    private decimal rField;
    
    private decimal gField;
    
    private decimal bField;
    
    private byte aField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal r {
        get {
            return this.rField;
        }
        set {
            this.rField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal g {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte a {
        get {
            return this.aField;
        }
        set {
            this.aField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentViewport {
    
    private sceneEnvironmentViewportColour colourField;
    
    private string nameField;
    
    private uint idField;
    
    private byte indexField;
    
    /// <remarks/>
    public sceneEnvironmentViewportColour colour {
        get {
            return this.colourField;
        }
        set {
            this.colourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentViewportColour {
    
    private byte rField;
    
    private byte gField;
    
    private byte bField;
    
    private byte aField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte r {
        get {
            return this.rField;
        }
        set {
            this.rField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte g {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte a {
        get {
            return this.aField;
        }
        set {
            this.aField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentCamera {
    
    private sceneEnvironmentCameraClipping clippingField;
    
    private sceneEnvironmentCameraPosition positionField;
    
    private sceneEnvironmentCameraRotation rotationField;
    
    private string nameField;
    
    private byte viewModeField;
    
    private byte polyModeField;
    
    private byte fovField;
    
    /// <remarks/>
    public sceneEnvironmentCameraClipping clipping {
        get {
            return this.clippingField;
        }
        set {
            this.clippingField = value;
        }
    }
    
    /// <remarks/>
    public sceneEnvironmentCameraPosition position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public sceneEnvironmentCameraRotation rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte viewMode {
        get {
            return this.viewModeField;
        }
        set {
            this.viewModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte polyMode {
        get {
            return this.polyModeField;
        }
        set {
            this.polyModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fov {
        get {
            return this.fovField;
        }
        set {
            this.fovField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentCameraClipping {
    
    private decimal nearField;
    
    private ushort farField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal near {
        get {
            return this.nearField;
        }
        set {
            this.nearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort far {
        get {
            return this.farField;
        }
        set {
            this.farField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentCameraPosition {
    
    private decimal xField;
    
    private decimal yField;
    
    private decimal zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneEnvironmentCameraRotation {
    
    private decimal qwField;
    
    private decimal qxField;
    
    private decimal qyField;
    
    private decimal qzField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qw {
        get {
            return this.qwField;
        }
        set {
            this.qwField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qx {
        get {
            return this.qxField;
        }
        set {
            this.qxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qy {
        get {
            return this.qyField;
        }
        set {
            this.qyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qz {
        get {
            return this.qzField;
        }
        set {
            this.qzField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneTerrain {
    
    private sceneTerrainTerrainPages terrainPagesField;
    
    private ushort worldSizeField;
    
    private ushort mapSizeField;
    
    private string pagenameprefixField;
    
    private bool colourmapEnabledField;
    
    private byte colourMapTextureSizeField;
    
    private ushort tuningCompositeMapDistanceField;
    
    private byte tuningMaxPixelErrorField;
    
    private byte tuningMinBatchSizeField;
    
    private byte tuningMaxBatchSizeField;
    
    private byte tuningSkirtSizeField;
    
    private bool tuningUseRayBoxDistancealculationField;
    
    /// <remarks/>
    public sceneTerrainTerrainPages terrainPages {
        get {
            return this.terrainPagesField;
        }
        set {
            this.terrainPagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort worldSize {
        get {
            return this.worldSizeField;
        }
        set {
            this.worldSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort mapSize {
        get {
            return this.mapSizeField;
        }
        set {
            this.mapSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pagenameprefix {
        get {
            return this.pagenameprefixField;
        }
        set {
            this.pagenameprefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool colourmapEnabled {
        get {
            return this.colourmapEnabledField;
        }
        set {
            this.colourmapEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte colourMapTextureSize {
        get {
            return this.colourMapTextureSizeField;
        }
        set {
            this.colourMapTextureSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort tuningCompositeMapDistance {
        get {
            return this.tuningCompositeMapDistanceField;
        }
        set {
            this.tuningCompositeMapDistanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte tuningMaxPixelError {
        get {
            return this.tuningMaxPixelErrorField;
        }
        set {
            this.tuningMaxPixelErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte tuningMinBatchSize {
        get {
            return this.tuningMinBatchSizeField;
        }
        set {
            this.tuningMinBatchSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte tuningMaxBatchSize {
        get {
            return this.tuningMaxBatchSizeField;
        }
        set {
            this.tuningMaxBatchSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte tuningSkirtSize {
        get {
            return this.tuningSkirtSizeField;
        }
        set {
            this.tuningSkirtSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool tuningUseRayBoxDistancealculation {
        get {
            return this.tuningUseRayBoxDistancealculationField;
        }
        set {
            this.tuningUseRayBoxDistancealculationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneTerrainTerrainPages {
    
    private sceneTerrainTerrainPagesTerrainPage terrainPageField;
    
    /// <remarks/>
    public sceneTerrainTerrainPagesTerrainPage terrainPage {
        get {
            return this.terrainPageField;
        }
        set {
            this.terrainPageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneTerrainTerrainPagesTerrainPage {
    
    private string nameField;
    
    private byte pageXField;
    
    private byte pageYField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte pageX {
        get {
            return this.pageXField;
        }
        set {
            this.pageXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte pageY {
        get {
            return this.pageYField;
        }
        set {
            this.pageYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneLight {
    
    private sceneLightPosition positionField;
    
    private sceneLightDirectionVector directionVectorField;
    
    private sceneLightColourDiffuse colourDiffuseField;
    
    private sceneLightColourSpecular colourSpecularField;
    
    private string nameField;
    
    private uint idField;
    
    private string typeField;
    
    private bool castShadowsField;
    
    /// <remarks/>
    public sceneLightPosition position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public sceneLightDirectionVector directionVector {
        get {
            return this.directionVectorField;
        }
        set {
            this.directionVectorField = value;
        }
    }
    
    /// <remarks/>
    public sceneLightColourDiffuse colourDiffuse {
        get {
            return this.colourDiffuseField;
        }
        set {
            this.colourDiffuseField = value;
        }
    }
    
    /// <remarks/>
    public sceneLightColourSpecular colourSpecular {
        get {
            return this.colourSpecularField;
        }
        set {
            this.colourSpecularField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool castShadows {
        get {
            return this.castShadowsField;
        }
        set {
            this.castShadowsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneLightPosition {
    
    private decimal xField;
    
    private decimal yField;
    
    private decimal zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneLightDirectionVector {
    
    private byte xField;
    
    private decimal yField;
    
    private decimal zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneLightColourDiffuse {
    
    private byte rField;
    
    private byte gField;
    
    private byte bField;
    
    private byte aField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte r {
        get {
            return this.rField;
        }
        set {
            this.rField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte g {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte a {
        get {
            return this.aField;
        }
        set {
            this.aField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneLightColourSpecular {
    
    private byte rField;
    
    private byte gField;
    
    private byte bField;
    
    private byte aField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte r {
        get {
            return this.rField;
        }
        set {
            this.rField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte g {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte a {
        get {
            return this.aField;
        }
        set {
            this.aField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneCamera {
    
    private sceneCameraPosition positionField;
    
    private sceneCameraRotation rotationField;
    
    private sceneCameraClipping clippingField;
    
    private string nameField;
    
    private uint idField;
    
    private byte fovField;
    
    private string projectionTypeField;
    
    /// <remarks/>
    public sceneCameraPosition position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public sceneCameraRotation rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    public sceneCameraClipping clipping {
        get {
            return this.clippingField;
        }
        set {
            this.clippingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fov {
        get {
            return this.fovField;
        }
        set {
            this.fovField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string projectionType {
        get {
            return this.projectionTypeField;
        }
        set {
            this.projectionTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneCameraPosition {
    
    private decimal xField;
    
    private decimal yField;
    
    private decimal zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneCameraRotation {
    
    private decimal qwField;
    
    private decimal qxField;
    
    private decimal qyField;
    
    private decimal qzField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qw {
        get {
            return this.qwField;
        }
        set {
            this.qwField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qx {
        get {
            return this.qxField;
        }
        set {
            this.qxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qy {
        get {
            return this.qyField;
        }
        set {
            this.qyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qz {
        get {
            return this.qzField;
        }
        set {
            this.qzField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneCameraClipping {
    
    private decimal nearField;
    
    private byte farField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal near {
        get {
            return this.nearField;
        }
        set {
            this.nearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte far {
        get {
            return this.farField;
        }
        set {
            this.farField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneNode {
    
    private sceneNodePosition positionField;
    
    private sceneNodeRotation rotationField;
    
    private sceneNodeScale scaleField;
    
    private sceneNodeEntity entityField;
    
    private string nameField;
    
    private uint idField;
    
    /// <remarks/>
    public sceneNodePosition position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public sceneNodeRotation rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    public sceneNodeScale scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    public sceneNodeEntity entity {
        get {
            return this.entityField;
        }
        set {
            this.entityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneNodePosition {
    
    private decimal xField;
    
    private decimal yField;
    
    private decimal zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneNodeRotation {
    
    private decimal qwField;
    
    private byte qxField;
    
    private decimal qyField;
    
    private byte qzField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qw {
        get {
            return this.qwField;
        }
        set {
            this.qwField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte qx {
        get {
            return this.qxField;
        }
        set {
            this.qxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal qy {
        get {
            return this.qyField;
        }
        set {
            this.qyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte qz {
        get {
            return this.qzField;
        }
        set {
            this.qzField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneNodeScale {
    
    private decimal xField;
    
    private decimal yField;
    
    private decimal zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneNodeEntity {
    
    private sceneNodeEntitySubentity[] subentityField;
    
    private string nameField;
    
    private string meshFileField;
    
    private bool castShadowsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("subentity")]
    public sceneNodeEntitySubentity[] subentity {
        get {
            return this.subentityField;
        }
        set {
            this.subentityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string meshFile {
        get {
            return this.meshFileField;
        }
        set {
            this.meshFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool castShadows {
        get {
            return this.castShadowsField;
        }
        set {
            this.castShadowsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class sceneNodeEntitySubentity {
    
    private byte indexField;
    
    private string materialNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string materialName {
        get {
            return this.materialNameField;
        }
        set {
            this.materialNameField = value;
        }
    }
}
