//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.MDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gameDataEntities : DbContext
    {
        public gameDataEntities()
            : base("name=gameDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Fog> Fog { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Race> Race { get; set; }
        public DbSet<Sky> Sky { get; set; }
        public DbSet<Terrain> Terrain { get; set; }
        public DbSet<MatUsedInScene> MatUsedInScene { get; set; }
        public DbSet<Scene> Scene { get; set; }
        public DbSet<SceneNodes> SceneNodes { get; set; }
        public DbSet<GameEntity> GameEntity { get; set; }
    }
}
