//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.MDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbDataEntities : DbContext
    {
        public dbDataEntities()
            : base("name=dbDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Entity> Entity { get; set; }
        public DbSet<EntityData> EntityData { get; set; }
        public DbSet<Fog> Fog { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<SceneNode> SceneNode { get; set; }
        public DbSet<Sky> Sky { get; set; }
        public DbSet<Terrain> Terrain { get; set; }
        public DbSet<MatUsedInScene> MatUsedInScene { get; set; }
        public DbSet<Scene> Scene { get; set; }
    }
}
