//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDE.DAL.MDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gameDataEntities : DbContext
    {
        public gameDataEntities()
            : base("name=gameDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Entities> Entities { get; set; }
        public DbSet<EntitiyDyn> EntitiyDyn { get; set; }
        public DbSet<EntitiyStatic> EntitiyStatic { get; set; }
        public DbSet<EntityChar> EntityChar { get; set; }
        public DbSet<Games> Games { get; set; }
        public DbSet<Meshes> Meshes { get; set; }
        public DbSet<MeshToChar> MeshToChar { get; set; }
        public DbSet<PhysicObject> PhysicObject { get; set; }
        public DbSet<Race> Race { get; set; }
        public DbSet<Scenes> Scenes { get; set; }
    }
}
