//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDE.DAL.MDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityChar
    {
        public long EC_ID { get; set; }
        public Nullable<decimal> RID { get; set; }
        public Nullable<decimal> CID { get; set; }
        public byte[] Data { get; set; }
    }
}
