//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.MDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public long EntID { get; set; }
        public Nullable<decimal> EntType { get; set; }
        public string Name { get; set; }
        public Nullable<long> EntDID { get; set; }
        public byte[] Data { get; set; }
    }
}
