
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.MDB
{

using System;
    using System.Collections.Generic;
    
public partial class GameEntity
{

    public long EntID { get; set; }

    public Nullable<decimal> EntType { get; set; }

    public string Name { get; set; }

    public byte[] Data { get; set; }

    public Nullable<long> RaceID { get; set; }

}

}
