//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.MDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scene
    {
        public long SceneID { get; set; }
        public Nullable<long> FogID { get; set; }
        public Nullable<long> SkyID { get; set; }
        public Nullable<long> TerrID { get; set; }
        public byte[] Data { get; set; }
    }
}
