//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.MDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SceneNodes
    {
        public long NodeID { get; set; }
        public Nullable<long> SceneID { get; set; }
        public Nullable<long> EntID { get; set; }
        public byte[] Data { get; set; }
        public string Name { get; set; }
    }
}
