//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDE.DAL.MDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLITEADMIN_QUERIES
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string SQL { get; set; }
    }
}
