//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameEntity.proto
namespace GameEntity
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vec3f")]
  public partial class Vec3f : global::ProtoBuf.IExtensible
  {
    public Vec3f() {}
    
    private float _x = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quat4f")]
  public partial class Quat4f : global::ProtoBuf.IExtensible
  {
    public Quat4f() {}
    
    private float _w = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float w
    {
      get { return _w; }
      set { _w = value; }
    }
    private float _x = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Property")]
  public partial class Property : global::ProtoBuf.IExtensible
  {
    public Property() {}
    
    private string _type = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransformStateData")]
  public partial class TransformStateData : global::ProtoBuf.IExtensible
  {
    public TransformStateData() {}
    
    private Quat4f _rot = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Quat4f rot
    {
      get { return _rot; }
      set { _rot = value; }
    }
    private Vec3f _loc = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vec3f loc
    {
      get { return _loc; }
      set { _loc = value; }
    }
    private Vec3f _scl = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vec3f scl
    {
      get { return _scl; }
      set { _scl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PhysicsObject")]
  public partial class PhysicsObject : global::ProtoBuf.IExtensible
  {
    public PhysicsObject() {}
    
    private uint _colMask;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"colMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colMask
    {
      get { return _colMask; }
      set { _colMask = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _mode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private int _shape;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private float _mass;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mass", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float mass
    {
      get { return _mass; }
      set { _mass = value; }
    }
    private float _margin = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"margin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float margin
    {
      get { return _margin; }
      set { _margin = value; }
    }
    private float _radius;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private float _angularDamp = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"angularDamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angularDamp
    {
      get { return _angularDamp; }
      set { _angularDamp = value; }
    }
    private float _linearDamp = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"linearDamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float linearDamp
    {
      get { return _linearDamp; }
      set { _linearDamp = value; }
    }
    private float _formFactor = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"formFactor", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float formFactor
    {
      get { return _formFactor; }
      set { _formFactor = value; }
    }
    private float _minVel = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"minVel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float minVel
    {
      get { return _minVel; }
      set { _minVel = value; }
    }
    private float _maxVel = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"maxVel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float maxVel
    {
      get { return _maxVel; }
      set { _maxVel = value; }
    }
    private float _restitution;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"restitution", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float restitution
    {
      get { return _restitution; }
      set { _restitution = value; }
    }
    private float _friction;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"friction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float friction
    {
      get { return _friction; }
      set { _friction = value; }
    }
    private uint _colGroupMask;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"colGroupMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colGroupMask
    {
      get { return _colGroupMask; }
      set { _colGroupMask = value; }
    }
    private float _charStepHeight = default(float);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"charStepHeight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charStepHeight
    {
      get { return _charStepHeight; }
      set { _charStepHeight = value; }
    }
    private float _charJumpSpeed = default(float);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"charJumpSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charJumpSpeed
    {
      get { return _charJumpSpeed; }
      set { _charJumpSpeed = value; }
    }
    private float _charFallSpeed = default(float);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"charFallSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charFallSpeed
    {
      get { return _charFallSpeed; }
      set { _charFallSpeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEntity")]
  public partial class GameEntity : global::ProtoBuf.IExtensible
  {
    public GameEntity() {}
    
    private TransformStateData _transform = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"transform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TransformStateData transform
    {
      get { return _transform; }
      set { _transform = value; }
    }
    private int _mode = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private byte[] _findPathFlag = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"findPathFlag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] findPathFlag
    {
      get { return _findPathFlag; }
      set { _findPathFlag = value; }
    }
    private int _parent = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"parent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int parent
    {
      get { return _parent; }
      set { _parent = value; }
    }
    private string _boneParent = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"boneParent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string boneParent
    {
      get { return _boneParent; }
      set { _boneParent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}