//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PhysicsObject.proto
namespace PhysicsObject
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PhysicsObject")]
  public partial class PhysicsObject : global::ProtoBuf.IExtensible
  {
    public PhysicsObject() {}
    
    private uint _colMask;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"colMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colMask
    {
      get { return _colMask; }
      set { _colMask = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _shape;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private float _mass;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mass", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float mass
    {
      get { return _mass; }
      set { _mass = value; }
    }
    private float _margin = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"margin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float margin
    {
      get { return _margin; }
      set { _margin = value; }
    }
    private float _radius;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private float _angularDamp = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"angularDamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angularDamp
    {
      get { return _angularDamp; }
      set { _angularDamp = value; }
    }
    private float _linearDamp = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"linearDamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float linearDamp
    {
      get { return _linearDamp; }
      set { _linearDamp = value; }
    }
    private float _formFactor = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"formFactor", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float formFactor
    {
      get { return _formFactor; }
      set { _formFactor = value; }
    }
    private float _minVel = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"minVel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float minVel
    {
      get { return _minVel; }
      set { _minVel = value; }
    }
    private float _maxVel = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"maxVel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float maxVel
    {
      get { return _maxVel; }
      set { _maxVel = value; }
    }
    private float _restitution;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"restitution", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float restitution
    {
      get { return _restitution; }
      set { _restitution = value; }
    }
    private float _friction;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"friction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float friction
    {
      get { return _friction; }
      set { _friction = value; }
    }
    private uint _colGroupMask;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"colGroupMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colGroupMask
    {
      get { return _colGroupMask; }
      set { _colGroupMask = value; }
    }
    private float _charStepHeight = default(float);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"charStepHeight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charStepHeight
    {
      get { return _charStepHeight; }
      set { _charStepHeight = value; }
    }
    private float _charJumpSpeed = default(float);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"charJumpSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charJumpSpeed
    {
      get { return _charJumpSpeed; }
      set { _charJumpSpeed = value; }
    }
    private float _charFallSpeed = default(float);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"charFallSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charFallSpeed
    {
      get { return _charFallSpeed; }
      set { _charFallSpeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}