//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoType.proto
namespace ProtoType
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vec3f")]
  public partial class Vec3f : global::ProtoBuf.IExtensible
  {
    public Vec3f() {}
    
    private float _x = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quat4f")]
  public partial class Quat4f : global::ProtoBuf.IExtensible
  {
    public Quat4f() {}
    
    private float _w = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float w
    {
      get { return _w; }
      set { _w = value; }
    }
    private float _x = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransformStateData")]
  public partial class TransformStateData : global::ProtoBuf.IExtensible
  {
    public TransformStateData() {}
    
    private ProtoType.Quat4f _rot = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Quat4f rot
    {
      get { return _rot; }
      set { _rot = value; }
    }
    private ProtoType.Vec3f _loc = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Vec3f loc
    {
      get { return _loc; }
      set { _loc = value; }
    }
    private ProtoType.Vec3f _scl = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Vec3f scl
    {
      get { return _scl; }
      set { _scl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Colour")]
  public partial class Colour : global::ProtoBuf.IExtensible
  {
    public Colour() {}
    
    private float _r = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"r", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float r
    {
      get { return _r; }
      set { _r = value; }
    }
    private float _g = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"g", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float g
    {
      get { return _g; }
      set { _g = value; }
    }
    private float _b = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float b
    {
      get { return _b; }
      set { _b = value; }
    }
    private float _a = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a
    {
      get { return _a; }
      set { _a = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Clipping")]
  public partial class Clipping : global::ProtoBuf.IExtensible
  {
    public Clipping() {}
    
    private float _nearClip = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nearClip", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float nearClip
    {
      get { return _nearClip; }
      set { _nearClip = value; }
    }
    private float _farClip = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"farClip", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float farClip
    {
      get { return _farClip; }
      set { _farClip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PhysicsObject")]
  public partial class PhysicsObject : global::ProtoBuf.IExtensible
  {
    public PhysicsObject() {}
    
    private uint _colMask;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"colMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colMask
    {
      get { return _colMask; }
      set { _colMask = value; }
    }
    private ProtoType.PhysicsType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoType.PhysicsType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _mode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private int _shape;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private float _mass;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mass", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float mass
    {
      get { return _mass; }
      set { _mass = value; }
    }
    private float _margin = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"margin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float margin
    {
      get { return _margin; }
      set { _margin = value; }
    }
    private float _radius;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private float _angularDamp = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"angularDamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angularDamp
    {
      get { return _angularDamp; }
      set { _angularDamp = value; }
    }
    private float _linearDamp = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"linearDamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float linearDamp
    {
      get { return _linearDamp; }
      set { _linearDamp = value; }
    }
    private float _formFactor = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"formFactor", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float formFactor
    {
      get { return _formFactor; }
      set { _formFactor = value; }
    }
    private float _minVel = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"minVel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float minVel
    {
      get { return _minVel; }
      set { _minVel = value; }
    }
    private float _maxVel = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"maxVel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float maxVel
    {
      get { return _maxVel; }
      set { _maxVel = value; }
    }
    private float _restitution;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"restitution", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float restitution
    {
      get { return _restitution; }
      set { _restitution = value; }
    }
    private float _friction;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"friction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float friction
    {
      get { return _friction; }
      set { _friction = value; }
    }
    private uint _colGroupMask;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"colGroupMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colGroupMask
    {
      get { return _colGroupMask; }
      set { _colGroupMask = value; }
    }
    private float _charStepHeight = default(float);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"charStepHeight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charStepHeight
    {
      get { return _charStepHeight; }
      set { _charStepHeight = value; }
    }
    private float _charJumpSpeed = default(float);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"charJumpSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charJumpSpeed
    {
      get { return _charJumpSpeed; }
      set { _charJumpSpeed = value; }
    }
    private float _charFallSpeed = default(float);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"charFallSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charFallSpeed
    {
      get { return _charFallSpeed; }
      set { _charFallSpeed = value; }
    }
    private string _boneparent = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"boneparent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string boneparent
    {
      get { return _boneparent; }
      set { _boneparent = value; }
    }
    private string _collMeshName = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"collMeshName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string collMeshName
    {
      get { return _collMeshName; }
      set { _collMeshName = value; }
    }
    private ProtoType.Vec3f _size = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Vec3f size
    {
      get { return _size; }
      set { _size = value; }
    }
    private ProtoType.Vec3f _scale = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Vec3f scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private ProtoType.Vec3f _offset = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Vec3f offset
    {
      get { return _offset; }
      set { _offset = value; }
    }
    private bool _parentIsNode = default(bool);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"parentIsNode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool parentIsNode
    {
      get { return _parentIsNode; }
      set { _parentIsNode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mesh")]
  public partial class Mesh : global::ProtoBuf.IExtensible
  {
    public Mesh() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _RessGrp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RessGrp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RessGrp
    {
      get { return _RessGrp; }
      set { _RessGrp = value; }
    }
    private ProtoType.OgrePlane _plane = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"plane", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.OgrePlane plane
    {
      get { return _plane; }
      set { _plane = value; }
    }
    private ProtoType.OgreCube _cube = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cube", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.OgreCube cube
    {
      get { return _cube; }
      set { _cube = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StaticEntity")]
  public partial class StaticEntity : global::ProtoBuf.IExtensible
  {
    public StaticEntity() {}
    
    private ProtoType.GameEntity _gameEntity;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameEntity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.GameEntity gameEntity
    {
      get { return _gameEntity; }
      set { _gameEntity = value; }
    }
    private int _group = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int group
    {
      get { return _group; }
      set { _group = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Sound")]
  public partial class Sound : global::ProtoBuf.IExtensible
  {
    public Sound() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _fileName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }
    private string _ressGrp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ressGrp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ressGrp
    {
      get { return _ressGrp; }
      set { _ressGrp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Face")]
  public partial class Face : global::ProtoBuf.IExtensible
  {
    public Face() {}
    
    private string _textName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"textName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string textName
    {
      get { return _textName; }
      set { _textName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Skin")]
  public partial class Skin : global::ProtoBuf.IExtensible
  {
    public Skin() {}
    
    private string _textName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"textName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string textName
    {
      get { return _textName; }
      set { _textName = value; }
    }
    private string _mesh;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HairColor")]
  public partial class HairColor : global::ProtoBuf.IExtensible
  {
    public HairColor() {}
    
    private string _textName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"textName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string textName
    {
      get { return _textName; }
      set { _textName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HairStyle")]
  public partial class HairStyle : global::ProtoBuf.IExtensible
  {
    public HairStyle() {}
    
    private string _mesh;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FacialFeature")]
  public partial class FacialFeature : global::ProtoBuf.IExtensible
  {
    public FacialFeature() {}
    
    private string _mesh;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FacialColor")]
  public partial class FacialColor : global::ProtoBuf.IExtensible
  {
    public FacialColor() {}
    
    private string _textName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"textName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string textName
    {
      get { return _textName; }
      set { _textName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Shoulder")]
  public partial class Shoulder : global::ProtoBuf.IExtensible
  {
    public Shoulder() {}
    
    private string _mesh;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Boots")]
  public partial class Boots : global::ProtoBuf.IExtensible
  {
    public Boots() {}
    
    private string _mesh;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneHandWeapon")]
  public partial class OneHandWeapon : global::ProtoBuf.IExtensible
  {
    public OneHandWeapon() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _mesh;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TwoHandWeapon")]
  public partial class TwoHandWeapon : global::ProtoBuf.IExtensible
  {
    public TwoHandWeapon() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _mesh;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Race")]
  public partial class Race : global::ProtoBuf.IExtensible
  {
    public Race() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _description;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpellEntity")]
  public partial class SpellEntity : global::ProtoBuf.IExtensible
  {
    public SpellEntity() {}
    
    private ProtoType.GameEntity _gameEntity;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameEntity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.GameEntity gameEntity
    {
      get { return _gameEntity; }
      set { _gameEntity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RaceGender")]
  public partial class RaceGender : global::ProtoBuf.IExtensible
  {
    public RaceGender() {}
    
    private ProtoType.Race _race;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"race", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Race race
    {
      get { return _race; }
      set { _race = value; }
    }
    private ProtoType.PhysicsObject _bodyPhys;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bodyPhys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.PhysicsObject bodyPhys
    {
      get { return _bodyPhys; }
      set { _bodyPhys = value; }
    }
    private ProtoType.PhysicsObject _footLPhys;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"footLPhys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.PhysicsObject footLPhys
    {
      get { return _footLPhys; }
      set { _footLPhys = value; }
    }
    private ProtoType.PhysicsObject _footRPhys;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"footRPhys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.PhysicsObject footRPhys
    {
      get { return _footRPhys; }
      set { _footRPhys = value; }
    }
    private ProtoType.PhysicsObject _HandLPhys;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"HandLPhys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.PhysicsObject HandLPhys
    {
      get { return _HandLPhys; }
      set { _HandLPhys = value; }
    }
    private ProtoType.PhysicsObject _HandRPhys;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"HandRPhys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.PhysicsObject HandRPhys
    {
      get { return _HandRPhys; }
      set { _HandRPhys = value; }
    }
    private float _turnSpeed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"turnSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float turnSpeed
    {
      get { return _turnSpeed; }
      set { _turnSpeed = value; }
    }
    private ProtoType.Gender _gender;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoType.Gender gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoType.Sound> _sounds = new global::System.Collections.Generic.List<ProtoType.Sound>();
    [global::ProtoBuf.ProtoMember(9, Name=@"sounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.Sound> sounds
    {
      get { return _sounds; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.Face> _faces = new global::System.Collections.Generic.List<ProtoType.Face>();
    [global::ProtoBuf.ProtoMember(10, Name=@"faces", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.Face> faces
    {
      get { return _faces; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.Skin> _skins = new global::System.Collections.Generic.List<ProtoType.Skin>();
    [global::ProtoBuf.ProtoMember(11, Name=@"skins", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.Skin> skins
    {
      get { return _skins; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.HairColor> _hairColors = new global::System.Collections.Generic.List<ProtoType.HairColor>();
    [global::ProtoBuf.ProtoMember(12, Name=@"hairColors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.HairColor> hairColors
    {
      get { return _hairColors; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.HairStyle> _hairStyles = new global::System.Collections.Generic.List<ProtoType.HairStyle>();
    [global::ProtoBuf.ProtoMember(13, Name=@"hairStyles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.HairStyle> hairStyles
    {
      get { return _hairStyles; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.FacialFeature> _facials = new global::System.Collections.Generic.List<ProtoType.FacialFeature>();
    [global::ProtoBuf.ProtoMember(14, Name=@"facials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.FacialFeature> facials
    {
      get { return _facials; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.FacialColor> _facialcolors = new global::System.Collections.Generic.List<ProtoType.FacialColor>();
    [global::ProtoBuf.ProtoMember(15, Name=@"facialcolors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.FacialColor> facialcolors
    {
      get { return _facialcolors; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.Shoulder> _shoulder = new global::System.Collections.Generic.List<ProtoType.Shoulder>();
    [global::ProtoBuf.ProtoMember(16, Name=@"shoulder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.Shoulder> shoulder
    {
      get { return _shoulder; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.Boots> _boots = new global::System.Collections.Generic.List<ProtoType.Boots>();
    [global::ProtoBuf.ProtoMember(17, Name=@"boots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.Boots> boots
    {
      get { return _boots; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.SpellEntity> _spells = new global::System.Collections.Generic.List<ProtoType.SpellEntity>();
    [global::ProtoBuf.ProtoMember(18, Name=@"spells", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.SpellEntity> spells
    {
      get { return _spells; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharEntity")]
  public partial class CharEntity : global::ProtoBuf.IExtensible
  {
    public CharEntity() {}
    
    private ProtoType.GameEntity _gameEntity;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameEntity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.GameEntity gameEntity
    {
      get { return _gameEntity; }
      set { _gameEntity = value; }
    }
    private ProtoType.RaceGender _gender;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.RaceGender gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private ProtoType.Face _face;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Face face
    {
      get { return _face; }
      set { _face = value; }
    }
    private ProtoType.Skin _skin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"skin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Skin skin
    {
      get { return _skin; }
      set { _skin = value; }
    }
    private ProtoType.HairColor _hairColor;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hairColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.HairColor hairColor
    {
      get { return _hairColor; }
      set { _hairColor = value; }
    }
    private ProtoType.HairStyle _hairStyle;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hairStyle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.HairStyle hairStyle
    {
      get { return _hairStyle; }
      set { _hairStyle = value; }
    }
    private ProtoType.FacialFeature _facialfeature;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"facialfeature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.FacialFeature facialfeature
    {
      get { return _facialfeature; }
      set { _facialfeature = value; }
    }
    private ProtoType.FacialColor _facialcolor;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"facialcolor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.FacialColor facialcolor
    {
      get { return _facialcolor; }
      set { _facialcolor = value; }
    }
    private ProtoType.Boots _boots;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"boots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Boots boots
    {
      get { return _boots; }
      set { _boots = value; }
    }
    private ProtoType.Shoulder _shoulderMesh;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"shoulderMesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Shoulder shoulderMesh
    {
      get { return _shoulderMesh; }
      set { _shoulderMesh = value; }
    }
    private ProtoType.OneHandWeapon _oneHLWeapon = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"oneHLWeapon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.OneHandWeapon oneHLWeapon
    {
      get { return _oneHLWeapon; }
      set { _oneHLWeapon = value; }
    }
    private ProtoType.OneHandWeapon _oneHRWeapon = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"oneHRWeapon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.OneHandWeapon oneHRWeapon
    {
      get { return _oneHRWeapon; }
      set { _oneHRWeapon = value; }
    }
    private ProtoType.TwoHandWeapon _twoHWeapon = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"twoHWeapon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.TwoHandWeapon twoHWeapon
    {
      get { return _twoHWeapon; }
      set { _twoHWeapon = value; }
    }
    private ProtoType.AI _ai = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"ai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.AI ai
    {
      get { return _ai; }
      set { _ai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AI")]
  public partial class AI : global::ProtoBuf.IExtensible
  {
    public AI() {}
    
    private string _scriptName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scriptName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string scriptName
    {
      get { return _scriptName; }
      set { _scriptName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnPoint")]
  public partial class SpawnPoint : global::ProtoBuf.IExtensible
  {
    public SpawnPoint() {}
    
    private int _SPGroup;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SPGroup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SPGroup
    {
      get { return _SPGroup; }
      set { _SPGroup = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Trigger")]
  public partial class Trigger : global::ProtoBuf.IExtensible
  {
    public Trigger() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OgrePlane")]
  public partial class OgrePlane : global::ProtoBuf.IExtensible
  {
    public OgrePlane() {}
    
    private ProtoType.Vec3f _normal;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"normal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Vec3f normal
    {
      get { return _normal; }
      set { _normal = value; }
    }
    private float _constant;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"constant", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float constant
    {
      get { return _constant; }
      set { _constant = value; }
    }
    private float _width;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float width
    {
      get { return _width; }
      set { _width = value; }
    }
    private float _height;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float height
    {
      get { return _height; }
      set { _height = value; }
    }
    private int _xsegments;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"xsegments", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xsegments
    {
      get { return _xsegments; }
      set { _xsegments = value; }
    }
    private int _ysegments;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ysegments", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ysegments
    {
      get { return _ysegments; }
      set { _ysegments = value; }
    }
    private bool _normals;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"normals", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool normals
    {
      get { return _normals; }
      set { _normals = value; }
    }
    private int _numTexCoordSets;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"numTexCoordSets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int numTexCoordSets
    {
      get { return _numTexCoordSets; }
      set { _numTexCoordSets = value; }
    }
    private float _xTile;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"xTile", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xTile
    {
      get { return _xTile; }
      set { _xTile = value; }
    }
    private float _yTile;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"yTile", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yTile
    {
      get { return _yTile; }
      set { _yTile = value; }
    }
    private ProtoType.Vec3f _upVector;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"upVector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Vec3f upVector
    {
      get { return _upVector; }
      set { _upVector = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OgreCube")]
  public partial class OgreCube : global::ProtoBuf.IExtensible
  {
    public OgreCube() {}
    
    private float _width;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float width
    {
      get { return _width; }
      set { _width = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OSysTypeData")]
  public partial class OSysTypeData : global::ProtoBuf.IExtensible
  {
    public OSysTypeData() {}
    
    private ProtoType.OgrePlane _plane;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"plane", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.OgrePlane plane
    {
      get { return _plane; }
      set { _plane = value; }
    }
    private ProtoType.OgreCube _cube;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cube", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.OgreCube cube
    {
      get { return _cube; }
      set { _cube = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Debug")]
  public partial class Debug : global::ProtoBuf.IExtensible
  {
    public Debug() {}
    
    private bool _Show = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Show", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Show
    {
      get { return _Show; }
      set { _Show = value; }
    }
    private bool _ShowAABB = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ShowAABB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ShowAABB
    {
      get { return _ShowAABB; }
      set { _ShowAABB = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Material")]
  public partial class Material : global::ProtoBuf.IExtensible
  {
    public Material() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _RessGrp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RessGrp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RessGrp
    {
      get { return _RessGrp; }
      set { _RessGrp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEntity")]
  public partial class GameEntity : global::ProtoBuf.IExtensible
  {
    public GameEntity() {}
    
    private readonly global::System.Collections.Generic.List<ProtoType.Mesh> _meshes = new global::System.Collections.Generic.List<ProtoType.Mesh>();
    [global::ProtoBuf.ProtoMember(1, Name=@"meshes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.Mesh> meshes
    {
      get { return _meshes; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.Sound> _sounds = new global::System.Collections.Generic.List<ProtoType.Sound>();
    [global::ProtoBuf.ProtoMember(2, Name=@"sounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.Sound> sounds
    {
      get { return _sounds; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.Material> _materials = new global::System.Collections.Generic.List<ProtoType.Material>();
    [global::ProtoBuf.ProtoMember(3, Name=@"materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.Material> materials
    {
      get { return _materials; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.PhysicsObject> _physics = new global::System.Collections.Generic.List<ProtoType.PhysicsObject>();
    [global::ProtoBuf.ProtoMember(4, Name=@"physics", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.PhysicsObject> physics
    {
      get { return _physics; }
    }
  
    private ProtoType.EntityTypes _Type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoType.EntityTypes Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _boneparent = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"boneparent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string boneparent
    {
      get { return _boneparent; }
      set { _boneparent = value; }
    }
    private int _mode;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private bool _castShadows = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"castShadows", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool castShadows
    {
      get { return _castShadows; }
      set { _castShadows = value; }
    }
    private ProtoType.Debug _debug = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"debug", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Debug debug
    {
      get { return _debug; }
      set { _debug = value; }
    }
    private string _animationTree = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"animationTree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string animationTree
    {
      get { return _animationTree; }
      set { _animationTree = value; }
    }
    private string _animationInfo = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"animationInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string animationInfo
    {
      get { return _animationInfo; }
      set { _animationInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Light")]
  public partial class Light : global::ProtoBuf.IExtensible
  {
    public Light() {}
    
    private ProtoType.Colour _colourDiffuse;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"colourDiffuse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Colour colourDiffuse
    {
      get { return _colourDiffuse; }
      set { _colourDiffuse = value; }
    }
    private ProtoType.Colour _colourSpecular;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"colourSpecular", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Colour colourSpecular
    {
      get { return _colourSpecular; }
      set { _colourSpecular = value; }
    }
    private ProtoType.Vec3f _directionVector;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"directionVector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Vec3f directionVector
    {
      get { return _directionVector; }
      set { _directionVector = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Fog")]
  public partial class Fog : global::ProtoBuf.IExtensible
  {
    public Fog() {}
    
    private int _mode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private ProtoType.Colour _colour = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"colour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Colour colour
    {
      get { return _colour; }
      set { _colour = value; }
    }
    private int _start = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int start
    {
      get { return _start; }
      set { _start = value; }
    }
    private int _end = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int end
    {
      get { return _end; }
      set { _end = value; }
    }
    private int _density = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"density", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int density
    {
      get { return _density; }
      set { _density = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camera")]
  public partial class Camera : global::ProtoBuf.IExtensible
  {
    public Camera() {}
    
    private ProtoType.Clipping _clipping;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clipping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Clipping clipping
    {
      get { return _clipping; }
      set { _clipping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Node")]
  public partial class Node : global::ProtoBuf.IExtensible
  {
    public Node() {}
    
    private ProtoType.TransformStateData _transform;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"transform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.TransformStateData transform
    {
      get { return _transform; }
      set { _transform = value; }
    }
    private bool _visible;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"visible", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool visible
    {
      get { return _visible; }
      set { _visible = value; }
    }
    private bool _enabled;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"enabled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool enabled
    {
      get { return _enabled; }
      set { _enabled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Scene")]
  public partial class Scene : global::ProtoBuf.IExtensible
  {
    public Scene() {}
    
    private ProtoType.Colour _colourAmbient;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"colourAmbient", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Colour colourAmbient
    {
      get { return _colourAmbient; }
      set { _colourAmbient = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetWindow")]
  public partial class SetWindow : global::ProtoBuf.IExtensible
  {
    public SetWindow() {}
    
    private bool _FullScreen;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FullScreen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool FullScreen
    {
      get { return _FullScreen; }
      set { _FullScreen = value; }
    }
    private ProtoType.VideoMode _VideoMode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"VideoMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoType.VideoMode VideoMode
    {
      get { return _VideoMode; }
      set { _VideoMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetGraphic")]
  public partial class SetGraphic : global::ProtoBuf.IExtensible
  {
    public SetGraphic() {}
    
    private ProtoType.AA _FSAA;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FSAA", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoType.AA FSAA
    {
      get { return _FSAA; }
      set { _FSAA = value; }
    }
    private bool _VSync;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"VSync", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool VSync
    {
      get { return _VSync; }
      set { _VSync = value; }
    }
    private int _ColourDepth;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ColourDepth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ColourDepth
    {
      get { return _ColourDepth; }
      set { _ColourDepth = value; }
    }
    private int _DispFreq;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DispFreq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DispFreq
    {
      get { return _DispFreq; }
      set { _DispFreq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Settings")]
  public partial class Settings : global::ProtoBuf.IExtensible
  {
    public Settings() {}
    
    private bool _ShowFPS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ShowFPS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ShowFPS
    {
      get { return _ShowFPS; }
      set { _ShowFPS = value; }
    }
    private ProtoType.SetGraphic _graphic;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"graphic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.SetGraphic graphic
    {
      get { return _graphic; }
      set { _graphic = value; }
    }
    private ProtoType.SetWindow _window;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"window", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.SetWindow window
    {
      get { return _window; }
      set { _window = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PhysicsType")]
    public enum PhysicsType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PT_NO_COLLISION", Value=0)]
      PT_NO_COLLISION = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PT_STATIC", Value=1)]
      PT_STATIC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PT_DYNAMIC", Value=2)]
      PT_DYNAMIC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PT_RIGID", Value=3)]
      PT_RIGID = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PT_SOFT", Value=4)]
      PT_SOFT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PT_SENSOR", Value=5)]
      PT_SENSOR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PT_NAVMESH", Value=6)]
      PT_NAVMESH = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PT_CHARACTER", Value=7)]
      PT_CHARACTER = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Gender")]
    public enum Gender
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Male", Value=0)]
      Male = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Female", Value=1)]
      Female = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Child", Value=2)]
      Child = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EntityTypes")]
    public enum EntityTypes
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Unkown", Value=0)]
      NT_Unkown = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Physic", Value=1)]
      NT_Physic = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Character", Value=2)]
      NT_Character = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Static", Value=3)]
      NT_Static = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Terrain", Value=4)]
      NT_Terrain = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Light", Value=5)]
      NT_Light = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Camera", Value=6)]
      NT_Camera = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AA")]
    public enum AA
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AA_off", Value=1)]
      AA_off = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AA_1X", Value=2)]
      AA_1X = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AA_2X", Value=3)]
      AA_2X = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AA_3X", Value=4)]
      AA_3X = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AA_4X", Value=5)]
      AA_4X = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AA_6X", Value=6)]
      AA_6X = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"VideoMode")]
    public enum VideoMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"VM_640X480", Value=1)]
      VM_640X480 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VM_800X600", Value=2)]
      VM_800X600 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VM_1024X768", Value=3)]
      VM_1024X768 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VM_1280X1024", Value=4)]
      VM_1280X1024 = 4
    }
  
}