//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoType.proto
namespace ProtoType
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vec3f")]
  public partial class Vec3f : global::ProtoBuf.IExtensible
  {
    public Vec3f() {}
    
    private float _x = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quat4f")]
  public partial class Quat4f : global::ProtoBuf.IExtensible
  {
    public Quat4f() {}
    
    private float _w = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float w
    {
      get { return _w; }
      set { _w = value; }
    }
    private float _x = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransformStateData")]
  public partial class TransformStateData : global::ProtoBuf.IExtensible
  {
    public TransformStateData() {}
    
    private ProtoType.Quat4f _rot = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Quat4f rot
    {
      get { return _rot; }
      set { _rot = value; }
    }
    private ProtoType.Vec3f _loc = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Vec3f loc
    {
      get { return _loc; }
      set { _loc = value; }
    }
    private ProtoType.Vec3f _scl = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Vec3f scl
    {
      get { return _scl; }
      set { _scl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Colour")]
  public partial class Colour : global::ProtoBuf.IExtensible
  {
    public Colour() {}
    
    private float _r = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"r", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float r
    {
      get { return _r; }
      set { _r = value; }
    }
    private float _g = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"g", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float g
    {
      get { return _g; }
      set { _g = value; }
    }
    private float _b = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float b
    {
      get { return _b; }
      set { _b = value; }
    }
    private float _a = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float a
    {
      get { return _a; }
      set { _a = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Clipping")]
  public partial class Clipping : global::ProtoBuf.IExtensible
  {
    public Clipping() {}
    
    private float _nearClip = (float)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nearClip", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float nearClip
    {
      get { return _nearClip; }
      set { _nearClip = value; }
    }
    private float _farClip = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"farClip", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float farClip
    {
      get { return _farClip; }
      set { _farClip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PhysicsObject")]
  public partial class PhysicsObject : global::ProtoBuf.IExtensible
  {
    public PhysicsObject() {}
    
    private uint _colMask;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"colMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colMask
    {
      get { return _colMask; }
      set { _colMask = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _mode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private int _shape;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private float _mass;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mass", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float mass
    {
      get { return _mass; }
      set { _mass = value; }
    }
    private float _margin = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"margin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float margin
    {
      get { return _margin; }
      set { _margin = value; }
    }
    private float _radius;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private float _angularDamp = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"angularDamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angularDamp
    {
      get { return _angularDamp; }
      set { _angularDamp = value; }
    }
    private float _linearDamp = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"linearDamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float linearDamp
    {
      get { return _linearDamp; }
      set { _linearDamp = value; }
    }
    private float _formFactor = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"formFactor", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float formFactor
    {
      get { return _formFactor; }
      set { _formFactor = value; }
    }
    private float _minVel = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"minVel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float minVel
    {
      get { return _minVel; }
      set { _minVel = value; }
    }
    private float _maxVel = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"maxVel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float maxVel
    {
      get { return _maxVel; }
      set { _maxVel = value; }
    }
    private float _restitution;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"restitution", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float restitution
    {
      get { return _restitution; }
      set { _restitution = value; }
    }
    private float _friction;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"friction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float friction
    {
      get { return _friction; }
      set { _friction = value; }
    }
    private uint _colGroupMask;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"colGroupMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colGroupMask
    {
      get { return _colGroupMask; }
      set { _colGroupMask = value; }
    }
    private float _charStepHeight = default(float);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"charStepHeight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charStepHeight
    {
      get { return _charStepHeight; }
      set { _charStepHeight = value; }
    }
    private float _charJumpSpeed = default(float);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"charJumpSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charJumpSpeed
    {
      get { return _charJumpSpeed; }
      set { _charJumpSpeed = value; }
    }
    private float _charFallSpeed = default(float);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"charFallSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float charFallSpeed
    {
      get { return _charFallSpeed; }
      set { _charFallSpeed = value; }
    }
    private string _boneparent = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"boneparent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string boneparent
    {
      get { return _boneparent; }
      set { _boneparent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StaticEntity")]
  public partial class StaticEntity : global::ProtoBuf.IExtensible
  {
    public StaticEntity() {}
    
    private ProtoType.GameEntity _gameEntity;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameEntity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.GameEntity gameEntity
    {
      get { return _gameEntity; }
      set { _gameEntity = value; }
    }
    private int _group = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int group
    {
      get { return _group; }
      set { _group = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnPoint")]
  public partial class SpawnPoint : global::ProtoBuf.IExtensible
  {
    public SpawnPoint() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Trigger")]
  public partial class Trigger : global::ProtoBuf.IExtensible
  {
    public Trigger() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEntity")]
  public partial class GameEntity : global::ProtoBuf.IExtensible
  {
    public GameEntity() {}
    
    private readonly global::System.Collections.Generic.List<string> _meshes = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"meshes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> meshes
    {
      get { return _meshes; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _sounds = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"sounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> sounds
    {
      get { return _sounds; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _materials = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> materials
    {
      get { return _materials; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoType.PhysicsObject> _physics = new global::System.Collections.Generic.List<ProtoType.PhysicsObject>();
    [global::ProtoBuf.ProtoMember(4, Name=@"physics", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoType.PhysicsObject> physics
    {
      get { return _physics; }
    }
  
    private ProtoType.EntityTypes _Type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoType.EntityTypes Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _boneparent = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"boneparent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string boneparent
    {
      get { return _boneparent; }
      set { _boneparent = value; }
    }
    private int _mode;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Light")]
  public partial class Light : global::ProtoBuf.IExtensible
  {
    public Light() {}
    
    private ProtoType.Colour _colourDiffuse;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"colourDiffuse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Colour colourDiffuse
    {
      get { return _colourDiffuse; }
      set { _colourDiffuse = value; }
    }
    private ProtoType.Colour _colourSpecular;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"colourSpecular", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Colour colourSpecular
    {
      get { return _colourSpecular; }
      set { _colourSpecular = value; }
    }
    private ProtoType.Vec3f _directionVector;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"directionVector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Vec3f directionVector
    {
      get { return _directionVector; }
      set { _directionVector = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Fog")]
  public partial class Fog : global::ProtoBuf.IExtensible
  {
    public Fog() {}
    
    private int _mode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private ProtoType.Colour _colour = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"colour", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoType.Colour colour
    {
      get { return _colour; }
      set { _colour = value; }
    }
    private int _start = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int start
    {
      get { return _start; }
      set { _start = value; }
    }
    private int _end = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int end
    {
      get { return _end; }
      set { _end = value; }
    }
    private int _density = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"density", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int density
    {
      get { return _density; }
      set { _density = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Camera")]
  public partial class Camera : global::ProtoBuf.IExtensible
  {
    public Camera() {}
    
    private ProtoType.Clipping _clipping;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clipping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Clipping clipping
    {
      get { return _clipping; }
      set { _clipping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Node")]
  public partial class Node : global::ProtoBuf.IExtensible
  {
    public Node() {}
    
    private ProtoType.TransformStateData _transform;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"transform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.TransformStateData transform
    {
      get { return _transform; }
      set { _transform = value; }
    }
    private int _EntityID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"EntityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EntityID
    {
      get { return _EntityID; }
      set { _EntityID = value; }
    }
    private bool _visible;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"visible", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool visible
    {
      get { return _visible; }
      set { _visible = value; }
    }
    private bool _enabled;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"enabled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool enabled
    {
      get { return _enabled; }
      set { _enabled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Scene")]
  public partial class Scene : global::ProtoBuf.IExtensible
  {
    public Scene() {}
    
    private ProtoType.Colour _colourAmbient;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"colourAmbient", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoType.Colour colourAmbient
    {
      get { return _colourAmbient; }
      set { _colourAmbient = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EntityTypes")]
    public enum EntityTypes
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Unkown", Value=0)]
      NT_Unkown = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Physic", Value=1)]
      NT_Physic = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Character", Value=2)]
      NT_Character = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Static", Value=3)]
      NT_Static = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Terrain", Value=4)]
      NT_Terrain = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Light", Value=5)]
      NT_Light = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NT_Camera", Value=6)]
      NT_Camera = 6
    }
  
}